### ISSUE TITLE
version of pdfminer

### ISSUE THREAD

**Issue by ejmurray** [mcs07/ChemDataExtractor#1]
Hi Matt.
The installation comes up with an error when I am installing using pip. pdfminer-20140328.tar.gz seems to be the problem.

Collecting pdfminer (from ChemDataExtractor)
  Using cached pdfminer-20140328.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ernest\AppData\Local\Temp\pip-build-uz7pty9c\pdfminer\setup.py", line 3, in <module>
        from pdfminer import __version__
      File "C:\Users\ernest\AppData\Local\Temp\pip-build-uz7pty9c\pdfminer\pdfminer\__init__.py", line 5
        print __version__
                        ^
    SyntaxError: Missing parentheses in call to 'print'

Could I install pdfminer.six OR pdfminer3k and use one of them instead?

**Comment by mcs07** [comment]
Fixing python 3 issues is high on my priority list. Either of those pdfminer alternatives should probably just work, but there may also be other minor problems with ChemDataExtractor itself because I haven't tested extensively under python 3. I will try and sort it out asap.

**Comment by ejmurray** [comment]
Thanks for the speedy reply.

**Comment by mcs07** [comment]
I think I have sorted this out. Will test further this evening and if all is good I'll push a new version.
