### ISSUE TITLE
installation failed, windows10,  "conda install -c chemdataextractor chemdataextractor"

### ISSUE THREAD

**Issue by dzhang228** [mcs07/ChemDataExtractor#24]
following your advice to issue #3, I installed anaconda, and run the command. But, solving environment failed, detailed output is listed below. Please help.
----------------------------------------
conda install -c chemdataextractor chemdataextractor
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> curl==7.63.0=h2a8f88b_1000 -> krb5[version='>=1.16.1,<1.17.0a0'] -> tk[version='>=8.6.7,<8.7.0a0']
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37hb782905_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37hdce8814_0
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> msvc_runtime
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> msgpack-python
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> chardet[version='>=3.0.2,<3.1.0']
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> idna[version='>=2.5,<2.7']
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> asn1crypto[version='>=0.21.0']
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> cffi[version='>=1.7'] -> pycparser
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> cryptography-vectors=2.3
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> enum34 -> ordereddict
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> ipaddress
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> packaging -> pyparsing
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> pyasn1[version='>=0.1.8']
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> six[version='>=1.4.1']
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> pyopenssl[version='>=0.14']
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23'] -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> win_inet_pton
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> colorama
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> distlib
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> distribute
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> html5lib -> webencodings
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> lockfile
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> progress
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> certifi
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> wincertstore
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> pip -> wheel
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='>=3.26.0,<4.0a0']
  - chemdataextractor -> appdirs -> python[version='>=2.7,<2.8.0a0'] -> vc=9
  - chemdataextractor -> beautifulsoup4 -> soupsieve -> backports.functools_lru_cache -> backports
  - chemdataextractor -> click
  - chemdataextractor -> lxml -> libxml2[version='>=2.9.4,<2.10.0a0'] -> libiconv[version='>=1.15,<2.0a0']
  - chemdataextractor -> lxml -> libxml2[version='>=2.9.4,<2.10.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - chemdataextractor -> lxml -> libxslt
  - chemdataextractor -> nltk -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> mkl_fft
  - chemdataextractor -> nltk -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> mkl_random
  - chemdataextractor -> nltk -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> numpy-base==1.11.3=py27hb1d0314_11
  - chemdataextractor -> nltk -> gensim -> scipy[version='>=0.18.1']
  - chemdataextractor -> nltk -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.7.0,<1.8.0'] -> docutils[version='>=0.10']
  - chemdataextractor -> nltk -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.7.0,<1.8.0'] -> python-dateutil[version='>=2.1,<3.0.0']
  - chemdataextractor -> nltk -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> s3transfer[version='>=0.1.10,<0.2.0'] -> futures[version='>=2.2.0,<4.0.0']
  - chemdataextractor -> nltk -> gensim -> smart_open[version='>=1.2.1'] -> boto[version='>=2.32']
  - chemdataextractor -> nltk -> matplotlib -> cycler[version='>=0.10']
  - chemdataextractor -> nltk -> matplotlib -> dateutil
  - chemdataextractor -> nltk -> matplotlib -> freetype[version='>=2.8,<2.9.0a0'] -> libpng[version='>=1.6.32,<1.7.0a0']
  - chemdataextractor -> nltk -> matplotlib -> functools32
  - chemdataextractor -> nltk -> matplotlib -> kiwisolver
  - chemdataextractor -> nltk -> matplotlib -> pyqt=5.6 -> qt=5.6 -> icu[version='>=58.2,<59.0a0']
  - chemdataextractor -> nltk -> matplotlib -> pyqt=5.6 -> qt=5.6 -> jpeg[version='>=9b,<10a']
  - chemdataextractor -> nltk -> matplotlib -> pyqt=5.6 -> sip=4.18
  - chemdataextractor -> nltk -> matplotlib -> pyside==1.1.2
  - chemdataextractor -> nltk -> matplotlib -> pytz
  - chemdataextractor -> nltk -> matplotlib -> subprocess32
  - chemdataextractor -> nltk -> matplotlib -> tk=8.5
  - chemdataextractor -> nltk -> matplotlib -> tornado -> backports_abc[version='>=0.4']
  - chemdataextractor -> nltk -> matplotlib -> tornado -> singledispatch
  - chemdataextractor -> nltk -> matplotlib -> tornado -> ssl_match_hostname
  - chemdataextractor -> nltk -> python-crfsuite -> *[track_features=vc10]
  - chemdataextractor -> nltk -> pyyaml -> yaml[version='>=0.1.7,<0.2.0a0']
  - chemdataextractor -> nltk -> scikit-learn -> nose
  - chemdataextractor -> nltk -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> configparser
  - chemdataextractor -> nltk -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> mccabe[version='>=0.6.0,<0.7.0']
  - chemdataextractor -> nltk -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> pep8
  - chemdataextractor -> nltk -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> pycodestyle[version='>=2.0.0,<2.4.0']
  - chemdataextractor -> nltk -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> pyflakes[version='>=1.5.0,<1.6.0']
Use "conda info <package>" to see the dependencies for each package.

**Comment by minnieswiftie** [comment]
Same here. pip install doesn't work either

**Comment by mcs07** [comment]
Should now be fixed, let me know if any issues persist.

By the way, ChemDataExtractor is now also available on the `conda-forge` channel. I will probably update the documentation to recommend installing from there as it has more automated maintenance.
